# Generated by Django 3.2.7 on 2021-12-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50, verbose_name='word searching')),
                ('searchs', models.IntegerField(verbose_name='num searchs')),
                ('result', models.JSONField(default={})),
                ('lastSearch', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
