# Generated by Django 3.2.7 on 2021-12-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_search_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searchs',
            field=models.IntegerField(default=1, null=True, verbose_name='num searchs'),
        ),
    ]
