# Generated by Django 3.2.7 on 2021-12-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_search_searchs'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='createSearch',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
